# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\ui\send_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_send_message(object):
    def setupUi(self, Form_send_message):
        Form_send_message.setObjectName("Form_send_message")
        Form_send_message.resize(564, 506)
        self.BodyLabel_ip = BodyLabel(Form_send_message)
        self.BodyLabel_ip.setGeometry(QtCore.QRect(25, 79, 65, 19))
        self.BodyLabel_ip.setObjectName("BodyLabel_ip")
        self.BodyLabel_port = BodyLabel(Form_send_message)
        self.BodyLabel_port.setGeometry(QtCore.QRect(240, 80, 65, 19))
        self.BodyLabel_port.setObjectName("BodyLabel_port")
        self.LineEdit_port = LineEdit(Form_send_message)
        self.LineEdit_port.setGeometry(QtCore.QRect(290, 70, 151, 33))
        self.LineEdit_port.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.LineEdit_port.setInputMask("")
        self.LineEdit_port.setText("")
        self.LineEdit_port.setMaxLength(32367)
        self.LineEdit_port.setObjectName("LineEdit_port")
        self.bodyLabel_message = BodyLabel(Form_send_message)
        self.bodyLabel_message.setGeometry(QtCore.QRect(320, 130, 101, 20))
        self.bodyLabel_message.setObjectName("bodyLabel_message")
        self.LineEdit_message = LineEdit(Form_send_message)
        self.LineEdit_message.setGeometry(QtCore.QRect(270, 160, 191, 33))
        self.LineEdit_message.setMaxLength(300)
        self.LineEdit_message.setObjectName("LineEdit_message")
        self.Button_Send = PrimaryPushButton(Form_send_message)
        self.Button_Send.setGeometry(QtCore.QRect(290, 210, 153, 32))
        self.Button_Send.setObjectName("Button_Send")
        self.ListWidget = ListWidget(Form_send_message)
        self.ListWidget.setGeometry(QtCore.QRect(60, 50, 171, 401))
        self.ListWidget.setObjectName("ListWidget")
        self.ProgressBar = ProgressBar(Form_send_message)
        self.ProgressBar.setGeometry(QtCore.QRect(240, 260, 231, 4))
        self.ProgressBar.setMinimum(0)
        self.ProgressBar.setMaximum(15)
        self.ProgressBar.setProperty("value", 15)
        self.ProgressBar.setObjectName("ProgressBar")
        self.ProgressRing = ProgressRing(Form_send_message)
        self.ProgressRing.setGeometry(QtCore.QRect(240, 310, 100, 100))
        self.ProgressRing.setTextVisible(True)
        self.ProgressRing.setObjectName("ProgressRing")
        self.sendNum = SpinBox(Form_send_message)
        self.sendNum.setGeometry(QtCore.QRect(350, 330, 161, 33))
        self.sendNum.setMinimum(1)
        self.sendNum.setMaximum(99999)
        self.sendNum.setObjectName("sendNum")
        self.BodyLabel_sengNum = BodyLabel(Form_send_message)
        self.BodyLabel_sengNum.setGeometry(QtCore.QRect(400, 300, 63, 19))
        self.BodyLabel_sengNum.setObjectName("BodyLabel_sengNum")
        self.ProgressBar_sendProcess = ProgressBar(Form_send_message)
        self.ProgressBar_sendProcess.setGeometry(QtCore.QRect(350, 380, 165, 4))
        self.ProgressBar_sendProcess.setObjectName("ProgressBar_sendProcess")
        self.PillPushButton_selectAll = PillPushButton(Form_send_message)
        self.PillPushButton_selectAll.setGeometry(QtCore.QRect(110, 10, 121, 30))
        self.PillPushButton_selectAll.setObjectName("PillPushButton_selectAll")
        self.PrimaryPushButton_load_ip = PrimaryPushButton(Form_send_message)
        self.PrimaryPushButton_load_ip.setGeometry(QtCore.QRect(20, 10, 71, 32))
        self.PrimaryPushButton_load_ip.setObjectName("PrimaryPushButton_load_ip")

        self.retranslateUi(Form_send_message)
        QtCore.QMetaObject.connectSlotsByName(Form_send_message)

    def retranslateUi(self, Form_send_message):
        _translate = QtCore.QCoreApplication.translate
        Form_send_message.setWindowTitle(_translate("Form_send_message", "Form"))
        self.BodyLabel_ip.setText(_translate("Form_send_message", "IP："))
        self.BodyLabel_port.setText(_translate("Form_send_message", "端口："))
        self.bodyLabel_message.setText(_translate("Form_send_message", "想发送的消息:"))
        self.Button_Send.setText(_translate("Form_send_message", "发送"))
        self.BodyLabel_sengNum.setText(_translate("Form_send_message", "发送次数"))
        self.PillPushButton_selectAll.setText(_translate("Form_send_message", "全选"))
        self.PrimaryPushButton_load_ip.setText(_translate("Form_send_message", "加载ip"))
from qfluentwidgets import BodyLabel, LineEdit, ListWidget, PillPushButton, PrimaryPushButton, ProgressBar, ProgressRing, SpinBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_send_message = QtWidgets.QWidget()
    ui = Ui_Form_send_message()
    ui.setupUi(Form_send_message)
    Form_send_message.show()
    sys.exit(app.exec_())
