# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form_Setting(object):
    def setupUi(self, Form_Setting):
        Form_Setting.setObjectName("Form_Setting")
        Form_Setting.resize(600, 500)
        self.Button_get_path = PrimaryPushButton(Form_Setting)
        self.Button_get_path.setGeometry(QtCore.QRect(380, 30, 153, 32))
        self.Button_get_path.setObjectName("Button_get_path")
        self.LineEdit_path = LineEdit(Form_Setting)
        self.LineEdit_path.setGeometry(QtCore.QRect(20, 30, 351, 33))
        self.LineEdit_path.setFocusPolicy(QtCore.Qt.NoFocus)
        self.LineEdit_path.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LineEdit_path.setObjectName("LineEdit_path")
        self.BodyLabel = BodyLabel(Form_Setting)
        self.BodyLabel.setGeometry(QtCore.QRect(20, 10, 91, 19))
        self.BodyLabel.setObjectName("BodyLabel")
        self.BodyLabel_2 = BodyLabel(Form_Setting)
        self.BodyLabel_2.setGeometry(QtCore.QRect(20, 80, 63, 19))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.SpinBox_time = SpinBox(Form_Setting)
        self.SpinBox_time.setGeometry(QtCore.QRect(20, 110, 511, 33))
        self.SpinBox_time.setObjectName("SpinBox_time")
        self.Button_submit = PrimaryPushButton(Form_Setting)
        self.Button_submit.setGeometry(QtCore.QRect(10, 380, 521, 32))
        self.Button_submit.setObjectName("Button_submit")
        self.BodyLabel_3 = BodyLabel(Form_Setting)
        self.BodyLabel_3.setGeometry(QtCore.QRect(20, 160, 91, 19))
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.ComboBox_run_type = ComboBox(Form_Setting)
        self.ComboBox_run_type.setGeometry(QtCore.QRect(20, 190, 511, 32))
        self.ComboBox_run_type.setObjectName("ComboBox_run_type")
        self.Button_setTheme = PrimaryPushButton(Form_Setting)
        self.Button_setTheme.setGeometry(QtCore.QRect(380, 250, 153, 32))
        self.Button_setTheme.setObjectName("Button_setTheme")
        self.Button_setThemeColor = PrimaryPushButton(Form_Setting)
        self.Button_setThemeColor.setGeometry(QtCore.QRect(380, 300, 153, 32))
        self.Button_setThemeColor.setObjectName("Button_setThemeColor")

        self.retranslateUi(Form_Setting)
        QtCore.QMetaObject.connectSlotsByName(Form_Setting)

    def retranslateUi(self, Form_Setting):
        _translate = QtCore.QCoreApplication.translate
        Form_Setting.setWindowTitle(_translate("Form_Setting", "Form"))
        self.Button_get_path.setText(_translate("Form_Setting", "查找"))
        self.BodyLabel.setText(_translate("Form_Setting", "IP列表路径"))
        self.BodyLabel_2.setText(_translate("Form_Setting", "延时时间"))
        self.Button_submit.setText(_translate("Form_Setting", "提交"))
        self.BodyLabel_3.setText(_translate("Form_Setting", "命令运行方式"))
        self.Button_setTheme.setText(_translate("Form_Setting", "修改主题样式"))
        self.Button_setThemeColor.setText(_translate("Form_Setting", "修改主题颜色"))


from qfluentwidgets import BodyLabel, ComboBox, LineEdit, PrimaryPushButton, SpinBox
